Visual Studio/Lyco/Controllers/HouseController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using pruebita.Models;
using System.Net;

namespace pruebita.Controllers
{
    public class HouseController : Controller
    {
        private readonly bdproyectoContext Context;

        public HouseController(bdproyectoContext Context)
        {
            this.Context = Context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Validar(UsuarioLogin usuario)
        {
            if (ModelState.IsValid)
            {
                var Obj = (from TUsuario in Context.Usuarios where TUsuario.PasswordUsuario == usuario.PasswordUsuario && TUsuario.CorreoUsuario ==usuario.CorreoUsuario select TUsuario).FirstOrDefault();

                if(Obj == null)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    HttpContext.Session.SetString("susuario",JsonConvert.SerializeObject(Obj));
                    return RedirectToAction(Obj.IdUsuario, "Interfaz"); 
                }

            }
            else
            {
                return View("Index");
            }
        }

        public IActionResult Register()
        {
            ViewBag.Tipo = Context.Tipousuarios;
            return View();
        }

        public IActionResult RegisterUsuario(Usuario Obj)
        {
            if (ModelState.IsValid)
            {
                Context.Usuarios.Add(Obj);
                Context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Tipo = Context.Tipousuarios;
                return View("Register");
            }
        }


        [Route("~/Interfaz/{id}")]
        public IActionResult Interfaz(string? id)
        {
            Console.Write("Holaa");
            var user = Context.Usuarios.Find(id);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Interfaz(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                return View(usuario);
            }

            return NotFound();
        }


        public IActionResult EditPerfil(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var obj = Context.Usuarios.Find(id);

            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult EditPerfil(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                Context.Usuarios.Update(usuario);
                Context.SaveChanges();
                return RedirectToAction(usuario.IdUsuario, "Interfaz");
            }

            return View(usuario);
        }
        

        [Route("~/Sesion/{id?}")]
        public IActionResult Sesion(string? id, string mode)
        {
            if (id == null)
            {
                return NotFound();
            }

            Console.Write("Hola" + mode);
            
            var obj = Context.Usuarios.Find(id);

            if (obj == null)
            {
                return NotFound();
            }

            ViewData["mode"] = mode;
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Sesion(Usuario user)
        {
            if (ModelState.IsValid)
            {
                return View(user);
            }

            return NotFound();
        }

    }

}

Visual Studio/Lyco/Views/House/Index.cshtml
@model pruebita.Models.Usuario

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<body>
    <div class="container">
        <form class="form-signin" action="/House/Validar" method="post">

            <h2 class="form-signin-heading">Sign in</h2>

            <label for="inputEmail" class="sr-only">Correo</label>
            <input type="text" asp-for="CorreoUsuario" class="form-control" placeholder="Correo" id="Correo" />
            <span asp-validation-for="CorreoUsuario" class="text-danger"></span>


            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" asp-for="PasswordUsuario" class="form-control" placeholder="Password" id="password" />
            <span asp-validation-for="PasswordUsuario" class="text-danger"></span>


            <button class="btn btn-lg btn-primary btn-block" type="submit">
                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Sign in
            </button>
            <a asp-action="Register">Registrate</a>
        </form>
    </div>
</body>
</html>

Visual Studio/Lyco/Views/House/Register.cshtml
@model pruebita.Models.Usuario
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
<body>
    <form asp-controller="House" asp-action="RegisterUsuario" method="post">
        <div class="form-group">
            <label for="formGroupExampleInput2">DNI</label>
            <input asp-for="IdUsuario" class="form-control" id="formGroupExampleInput2" placeholder="DNI">
            <span asp-validation-for="IdUsuario" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput2">Nombres</label>
            <input asp-for="NombreUsuario" class="form-control" id="formGroupExampleInput2" placeholder="Nombre usuario">
            <span asp-validation-for="NombreUsuario" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput2">Apellidos</label>
            <input asp-for="ApellidoUsuario" class="form-control" id="formGroupExampleInput2" placeholder="Apellidos usuario">
            <span asp-validation-for="ApellidoUsuario" class="text-danger"></span>

        </div>
        <div class="form-group">
            <label for="formGroupExampleInput2">Edad</label>
            <input asp-for="EdadUsuario" class="form-control" id="formGroupExampleInput2" placeholder="Edad">
            <span asp-validation-for="EdadUsuario" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput2">Nickname</label>
            <input asp-for="NombreusuarioUsuario" class="form-control" id="formGroupExampleInput2" placeholder="Nickname">
            <span asp-validation-for="NombreusuarioUsuario" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput2">Correo</label>
            <input asp-for="CorreoUsuario" class="form-control" id="formGroupExampleInput2" placeholder="Correo usuario">
            <span asp-validation-for="CorreoUsuario" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput2">Password</label>
            <input type = "Password" asp-for="PasswordUsuario" class="form-control" id="Password" placeholder="Password usuario">
            <span asp-validation-for="PasswordUsuario" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput2">Tipo Usuario</label>
            <select asp-for="TipoUsuario" class="form-control" id="formGroupExampleInput2" asp-items='@(new SelectList( ViewBag.Tipo,"TipoUsuario1","Desc"))'></select>
            <span asp-validation-for="TipoUsuario" class="text-danger"></span>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary" value="btn" name="grabar" data-toggle="modal" data-target="#exampleModal">Grabar</button>
        </div>

    </form>

</body>
</html>